env = Environment(CPPPATH=[
  '/usr/include/opencv'],
  CPPFLAGS='-Wall -std=c++14',
  LINKFLAGS='`pkg-config --libs opencv`')

env.Program("PointCloudConstructor",
  ["PointCloudConstructor.cpp","Image.cpp", "FeatureMatcher.cpp", "ByDistanceComparator.cpp"],
  LIBS = ["boost_filesystem", "boost_system"])

